const courses=[
["science","Sciences","Physique-Chimie — Les forces","Lycée","12 leçons","5 000 FCFA"],
["science","Sciences","Sciences Naturelles — Corps humain","Collège","10 leçons","Inclus Pro"],
["math","Maths","Mathématiques — Fonctions","Lycée","14 leçons","5 000 FCFA"],
["math","Maths","Maths — Méthodes fondamentales","Collège","12 leçons","Inclus Pro"],
["exam","Examens","Objectif DEF — Parcours intensif","9e année","8 semaines","10 000 FCFA"],
["exam","Examens","Objectif BAC — Révisions guidées","Terminale","8 semaines","15 000 FCFA"],
["skill","Méthodologie","Méthodologie de travail","Tous niveaux","6 modules","Inclus Pro"],
["skill","Méthodologie","Prise de parole & confiance","Jeunes","5 modules","5 000 FCFA"],
["science","Sciences","Sciences Naturelles — Bases","Collège","11 leçons","Inclus Pro"]];
function render(list){document.querySelector("#courseGrid").innerHTML=list.map((c,i)=>`<article class="course"><span class="tag">${c[1]}</span><h3>${c[2]}</h3><p>Vidéo + fiche + exercices corrigés + quiz + suivi de progression.</p><div class="meta">${c[3]} · ${c[4]} · <b>${c[5]}</b></div><br><button class="btn soft" onclick="course(${i})">Voir le parcours</button></article>`).join("")}
function filter(cat,el){document.querySelectorAll(".filters button").forEach(b=>b.classList.remove("active"));el.classList.add("active");render(cat==="all"?courses:courses.filter(c=>c[0]===cat))}
function course(i){const c=courses[i];document.querySelector("#modalContent").innerHTML=`<span class="eyebrow">${c[1]}</span><h2>${c[2]}</h2><p><b>Niveau :</b> ${c[3]}<br><b>Format :</b> ${c[4]}<br><b>Tarif :</b> ${c[5]}</p><p>Le parcours comprend des contenus pédagogiques structurés, des exercices, des quiz et un suivi de progression.</p><button class="btn primary" onclick="buy('${c[2]}')">Accéder au parcours</button>`;document.querySelector("#modal").style.display="grid"}
function openModal(type){let html=type==="parent"?`<h2>Espace Parent</h2><p>Suivez les résultats et la progression de votre enfant.</p><input placeholder="Téléphone"><button class="btn primary" onclick="alert('Démonstration : demande enregistrée')">Continuer</button>`:type==="teacher"?`<h2>Enseignant partenaire</h2><p>Déposez votre candidature pour créer et enseigner sur HamLearn.</p><input placeholder="Nom complet"><input placeholder="Matière enseignée"><input placeholder="Téléphone"><button class="btn primary" onclick="alert('Candidature enregistrée — démonstration')">Candidater</button>`:type==="login"?`<h2>Connexion</h2><input placeholder="Téléphone ou e-mail"><input type="password" placeholder="Mot de passe"><button class="btn primary" onclick="alert('Connexion — démonstration')">Se connecter</button>`:`<h2>Rejoindre HamLearn</h2><p>Inscrivez-vous à la liste pilote.</p><input placeholder="Nom complet"><input placeholder="Téléphone / WhatsApp"><input placeholder="E-mail"><button class="btn primary" onclick="alert('Inscription enregistrée — démonstration')">Rejoindre</button>`;document.querySelector("#modalContent").innerHTML=html;document.querySelector("#modal").style.display="grid"}
function buy(plan){document.querySelector("#modalContent").innerHTML=`<h2>${plan}</h2><p>Le prototype prépare le parcours de paiement. En production, on connectera une solution compatible avec les moyens de paiement ciblés au Mali.</p><input placeholder="Nom complet"><input placeholder="Téléphone"><button class="btn primary" onclick="alert('Commande enregistrée — démonstration')">Continuer vers le paiement</button>`;document.querySelector("#modal").style.display="grid"}
function closeModal(){document.querySelector("#modal").style.display="none"}render(courses);